version: '3.8'
services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test-hand-db
    volumes:
      - ./pg_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
