name: CI/CD Pipeline

on:
  push:
    branches: [pi-7-deliverables]

permissions:
  contents: read
  packages: write
  security-events: write

env:
  REGISTRY: ghcr.io

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      image_base: ${{ steps.vars.outputs.image_base }}
      pr_tag: ${{ steps.vars.outputs.pr_tag }}
      commit_sha: ${{ steps.vars.outputs.commit_sha }}
      commit_sha_short: ${{ steps.vars.outputs.commit_sha_short }}
      test_image_tag: ${{ steps.vars.outputs.test_image_tag }}
    steps:
      - name: Compute image vars
        id: vars
        shell: bash
        run: |
          set -euo pipefail
          ORG="$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')"
          REPO="hand-index"
          IMAGE_BASE="${REGISTRY}/${ORG}/${REPO}"
          echo "image_base=${IMAGE_BASE}" >> "$GITHUB_OUTPUT"
          if [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
            PR_NUM="${{ github.event.pull_request.number }}"
            PR_TAG="pr-${PR_NUM}-build"
            echo "pr_tag=${PR_TAG}" >> "$GITHUB_OUTPUT"
            echo "test_image_tag=${PR_TAG}" >> "$GITHUB_OUTPUT"
          fi
          if [ "${GITHUB_EVENT_NAME}" = "push" ]; then
            COMMIT_SHA="${GITHUB_SHA}"
            SHORT_SHA="${COMMIT_SHA:0:12}"
            echo "commit_sha=${COMMIT_SHA}" >> "$GITHUB_OUTPUT"
            echo "commit_sha_short=${SHORT_SHA}" >> "$GITHUB_OUTPUT"
            echo "test_image_tag=${SHORT_SHA}" >> "$GITHUB_OUTPUT"
          fi

  build:
    name: build
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push hand-index image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          labels: |
            org.opencontainers.image.title=Hand Index
            org.opencontainers.image.description=Hand Index application
            org.opencontainers.image.version=${{ github.ref_name }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.date.outputs.date }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.documentation=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.authors=${{ github.actor }}
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.vendor=Your Organization
            maintainer=${{ github.actor }}
          tags: |
            ${{ needs.setup.outputs.image_base }}:${{ needs.setup.outputs.test_image_tag }}
            ${{ needs.setup.outputs.image_base }}:latest